name = "TheBlockSurvival"
author = "Slash"
version = "1.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87e5f889a90921ee19b7d3b846a8844232cdc37b06b2529b1923d5a036dbc2fb"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["1.21.11"]
