name = "TBS-Client"
author = "Slash"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "747a5aa5a43f50cc5a260ae28e55d595a70a55945831c78a67329eea182d31ff"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["1.21.11"]
