name = "TheBlockSurvival"
author = "Slash"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "777bcd133eadaa06291a5e2c6aef06466032c0ab4289351c16adeb795934f3a2"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["1.21.11"]
